### ISSUE TITLE
API message requests

### ISSUE THREAD

**Issue by KyleYoung** [kicstart/OpenSpace#14]
Could we have "newShip","newTorpedo","shipDestroyed","torpedoDestroyed" added to the server? it would make the client side stuff a bit easier.

Also, confirm that the "welcome" message contains an array of current ships and torpedoes for initialization.

**Comment by jonotron** [comment]
This has been resolved by https://github.com/kicstart/OpenSpace/pull/16 with the exception of torpedoDestroyed. Need to decide if torpedoes should be destroyed if a ship self-destructs, or if they should continue on with consequence.
